# Generated by Django 5.2.7 on 2026-06-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='scanned URL')),
                ('domain', models.CharField(db_index=True, max_length=255, verbose_name='domain')),
                ('scan_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='scan date')),
                ('is_wordpress', models.BooleanField(default=False, verbose_name='is WordPress')),
                ('reachable', models.BooleanField(default=True, verbose_name='reachable')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='security score')),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('N/A', 'N/A')], default='N/A', max_length=3, verbose_name='grade')),
                ('high_count', models.PositiveSmallIntegerField(default=0, verbose_name='high issues')),
                ('medium_count', models.PositiveSmallIntegerField(default=0, verbose_name='medium issues')),
                ('low_count', models.PositiveSmallIntegerField(default=0, verbose_name='low issues')),
                ('summary', models.JSONField(blank=True, default=list, verbose_name='summary')),
            ],
            options={
                'verbose_name': 'scan record',
                'verbose_name_plural': 'scan records',
                'ordering': ['-scan_date'],
            },
        ),
    ]
